### ISSUE TITLE
Implement AKM init! functions

### ISSUE THREAD

**Issue by ufechner7** [OpenSourceAWE/KiteModels.jl#153]
- [x] for KPS3
- [x] for KPS4
- [ ] for KPS5
- [x] for SymbolicAWEModel
- [x] add tests

`init!(model::AKM; kwparams...)` One of the keyword parameters should be `prn::Bool` which can be used to enable or disable `@info` messages. The integrator of the model will be initialized.

**Comment by ufechner7** [comment]
Currently implemented:
```
function init_sim!(s::AKM; t_end=1.0, stiffness_factor=0.5, delta=0.0001, upwind_dir=-pi/2, prn=false)
function init_sim!(s::RamAirKite, measure::Measurement;
    solver=ifelse(s.set.quasi_static, FBDF(nlsolve=OrdinaryDiffEqNonlinearSolve.NLNewton(relax=0.4, max_iter=1000)), FBDF()), 
    adaptive=true, prn=true, precompile=false, remake=false, reload=false, lin_outputs=Num[]
)
```

**Comment by ufechner7** [comment]
Question: Why is the parameter measure needed?

The initial condition of the simulation is defined in the settings:
```yaml
initial:
    l_tether: 200.0        # initial tether length       [m]
    elevation: 63        # initial elevation angle   [deg]
    v_reel_out: 0.0        # initial reel out speed    [m/s]
    depower:   40.0        # initial depower settings    [%]
```
If there is some field missing, like `kite_distance`, we can add it.

Furthermore, why is a parameter solver needed? There is a section for it in the settings:
```
solver:
    abs_tol: 0.0006        # absolute tolerance of the DAE solver [m, m/s]
    rel_tol: 0.001         # relative tolerance of the DAE solver [-]
    solver: "DFBDF"        # DAE solver, IDA or DFBDF or DImplicitEuler
    linear_solver: "GMRES" # can be GMRES or LapackDense or Dense (only for IDA)
    max_order: 4           # maximal order, usually between 3 and 5 (IDA and DFBDF)
    max_iter:  200         # max number of iterations of the steady-state-solver
```
If there is a field missing, we can add it.
